import type { Metadata } from 'next';
import localFont from 'next/font/local';

/** styles */
import '../styles/globals.css';

const geistSans = localFont({
  src: '../fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: '../fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: {
    template: '%s | Next.js',
    default: 'Next.js',
  },
  description: 'Generated by create next app',
};

/**
 * 根布局在 app 目录的顶层定义，并适用于所有路由。
 * 此布局是必需的，并且必须包含 html 和 body 标记，从而允许您修改从服务器返回的初始 HTML
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>{children}</body>
    </html>
  );
}
